- db/migrate/20230307150311_remove_time_from_prescriptions.rb
- db/migrate/20230307150607_add_columns_to_prescriptions.rb
- db/schema.rb
> Changing the column time in prescriptions in two integer columns

- app/models/prescription.rb
- app/models/treatment.rb
- app/models/user.rb
- app/views/prescriptions/index.html.erb
theo.pills renvoie les bons traitements, alors que c'est la catégorie du traitement de la prescription de théo
> Defining methods to do .pills .cares and .exercises on a user instance

- app/models/doctor.rb
- app/models/treatment.rb
- app/models/user.rb
- db/migrate/20230308104656_add_title_to_doctors.rb
- db/migrate/20230308104739_add_user_to_doctors.rb
- db/schema.rb
- db/seeds.rb
J'ai ajouté les colonnes:
-title
-user_id pour qu'un utilisateur puisse créer ses docteurs préférés
> Migrations doctors

- public/404.html
- public/422.html
- public/500.html
> pimping the erro pages

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_prescription_card.scss
- app/controllers/prescriptions_controller.rb
- app/javascript/application.js
- app/models/prescription.rb
- app/views/pages/pills.html.erb
- db/seeds.rb
- package-lock.json
- package.json
- yarn.lock
J'ai réorganisé les heures disponibles dans le formulaire pour qu'il n'y ait pas de conflit AM/PM
> English hours

- db/migrate/20230313082639_remove_photo_from_diaries.rb
- db/schema.rb
- db/seeds.rb
- yarn.lock
Updated l'adresse des docteurs ;-)
> seed updated for doctors only

- db/seeds.rb
> created and updated the seed selfie

- db/seeds.rb
> diary new fixed the mistake

- app/assets/stylesheets/components/_form_new_prescription.scss
- app/javascript/controllers/form_controller.js
- app/javascript/controllers/init_tom_select_controller.js
- app/models/prescription.rb
- app/views/prescriptions/_form_prescription.html.erb
> adding tunnel effect for the category and treatment names

- app/assets/stylesheets/components/_diary.scss
- app/assets/stylesheets/components/_log_in.scss
- app/assets/stylesheets/components/_prescription_card.scss
- app/views/devise/sessions/new.html.erb
- app/views/pages/landing.html.erb
> bouton + texte + pills

- app/controllers/pages_controller.rb
- db/schema.rb
I have deleted the method calendars in pages controller as it is now in prescriptions index method in prescriptions controller
> deleted calendars method in pages controller

- app/assets/stylesheets/components/_form_appointment.scss
- app/assets/stylesheets/components/_form_prescription.scss
- app/views/appointments/_form_appointment.html.erb
- app/views/prescriptions/_form_prescription.html.erb
> beautifying the forms to have it as their simplest"

- app/views/layouts/application.html.erb
- db/seeds.rb
> changed the title website

- app/views/pages/home.html.erb
> i have deleted the community from navbar

- app/assets/stylesheets/components/_prescription_card.scss
- app/controllers/pages_controller.rb
- app/views/appointments/index.html.erb
- app/views/appointments/show.html.erb
- app/views/pages/boost.html.erb
résolutions problèmes pour la presse
> Boost marche plus

- app/assets/stylesheets/components/_reminder_next_prescriptions.scss
- app/assets/stylesheets/pages/_appointment.scss
- app/views/appointments/edit.html.erb
- app/views/prescriptions/edit.html.erb
- app/views/prescriptions/index.html.erb
- app/views/prescriptions/new.html.erb
> resolution problme

- app/controllers/appointments_controller.rb
- app/javascript/controllers/alert_confirm_controller.js
- app/javascript/controllers/index.js
- app/views/appointments/index.html.erb
- config/initializers/openweather.rb
> Heroku open weather error 

- app/assets/stylesheets/components/_boost.scss
- app/assets/stylesheets/components/_diary.scss
- app/views/diaries/show.html.erb
> pain scale

- app/assets/stylesheets/components/_reminder_next_prescriptions.scss
- app/controllers/appointments_controller.rb
- app/controllers/pages_controller.rb
- app/javascript/controllers/appointment_controller.js
- app/javascript/controllers/check_click_controller.js
- app/javascript/controllers/flatpickr_prescription_controller.js
- app/models/appointment.rb
- app/views/appointments/_form_appointment.html.erb
- app/views/pages/home.html.erb
- app/views/prescriptions/_form_prescription.html.erb
- db/seeds.rb
> Homepage real

- app/views/prescriptions/index.html.erb
- db/schema.rb
> buttons updated by theo yay

- app/assets/stylesheets/pages/_calendar_homepage.scss
homepage calendar fixed for today day and previous/next on the left/right sides
> css fixed for the today day yayy

- db/seeds.rb
**seed done for demo-day done** 
**_3 pills affected to diane :_** 
- codeine (date has expired on purpose so we can add codeine the d day)
- paracetamol ( affected to the d day)
- amoxiciline  ( affected to the d day)
**_2 cares affected to diane :_** 
- betadine
- bandage 
**_2 exercices affected to diane :_** 
- gentle walk
- mediatation  
**_I have created 2 new specialists :_** 
- Dr Estegassy en Post Op
- Nrs Hawks en Post Op Cares
_**2 appointments affected to diane :**_ 
- Post Op checking, ask when I can do sport again ( the day d) 
- The nurse will show me how to change the bandage ( the day after day d)
> seed done for demo-day

- app/views/layouts/application.html.erb
> the cover image is now working for meta

- config/initializers/openweather.rb
test with stack over flow solution for open map
>  test again

- config/initializers/openweather.rb
> solve localhost

- app/assets/stylesheets/components/_boost.scss
- app/assets/stylesheets/components/_diary.scss
- app/assets/stylesheets/components/_prescription_card.scss
- app/assets/stylesheets/pages/_calendar_homepage.scss
- app/assets/stylesheets/pages/_calendars_prescriptions.scss
- app/assets/stylesheets/pages/_home.scss
- app/javascript/controllers/index.js
- app/javascript/controllers/navbar_controller.js
- app/views/diaries/show.html.erb
- app/views/pages/boost.html.erb
- app/views/pages/home.html.erb
- app/views/prescriptions/index.html.erb
- app/views/simple_calendar/_week_calendar.html.erb
- db/schema.rb
> Navbar responsive

- app/javascript/controllers/alert_confirm_care_controller.js
- app/javascript/controllers/alert_exercise_controller.js
- app/javascript/controllers/confirm_pill_controller.js
> Fix swift alert

- config/initializers/openweather.rb
We are finidind solution open weather
> I am with sunny

- app/views/layouts/application.html.erb
> seed has changed 

- db/schema.rb
- db/seeds.rb
> done done done

- app/views/appointments/index.html.erb
- app/views/appointments/show.html.erb
- config/initializers/openweather.rb
weather care is done.need to design
> Weather mention
